{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.zhdanov",
    "module": "logging-starter-gradle",
    "version": "1.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-gradle-1.3-SNAPSHOT.jar",
          "url": "logging-starter-gradle-1.3-SNAPSHOT.jar",
          "size": 15345,
          "sha512": "bb011512758c6ae4fa133ed1f46e85e4166a22a0464413e607da18f74ee0297c66ea97e7d8ef3ab2a7ac68d2a3d810702fcd7ec41ea9c8fb9cdabf2b3c86db1d",
          "sha256": "4210d457bd35101413b52936d781622e1645bc4cfbef584a9b2741dae7926144",
          "sha1": "d5e16ca35e44726b9e108f4fab59defbbbfa19cf",
          "md5": "0c65d5217fa88fbc9d4f22743d638cf7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "logging-starter-gradle-1.3-SNAPSHOT.jar",
          "url": "logging-starter-gradle-1.3-SNAPSHOT.jar",
          "size": 15345,
          "sha512": "bb011512758c6ae4fa133ed1f46e85e4166a22a0464413e607da18f74ee0297c66ea97e7d8ef3ab2a7ac68d2a3d810702fcd7ec41ea9c8fb9cdabf2b3c86db1d",
          "sha256": "4210d457bd35101413b52936d781622e1645bc4cfbef584a9b2741dae7926144",
          "sha1": "d5e16ca35e44726b9e108f4fab59defbbbfa19cf",
          "md5": "0c65d5217fa88fbc9d4f22743d638cf7"
        }
      ]
    }
  ]
}
